teammanager/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from teams.views import HomePageView, TeamsListView, ScoresListView, PlayerDetailsView, TeamDetailsView, AddTeamView, \
    AddPlayerView

# Regular expression
# -     : case sensitive A != a
# \w    : alphabets, numbers & _ [A-Za-z0-9_]
# \x20  : an accept a space
# +     : compare all characters(digits)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name="home-page"),
    url(r'^teams/$', TeamsListView.as_view(), name="teams-list-view"),
    url(r'^scores/$', ScoresListView.as_view(), name="scores-list-view"),

    url(r'^player/(?P<slug>[-\w\x20]+)/$', PlayerDetailsView.as_view(), name="player-details-view"),
    url(r'^team/(?P<slug>[-\w\x20]+)/$', TeamDetailsView.as_view(), name="team-details-view"),

    url(r'^add_team/$', AddTeamView.as_view(), name="add-team-view"),
    url(r'^add_player/$', AddPlayerView.as_view(), name="add-player-view"),

]

teams/models.py
from django.db import models


# Create your models here.
from django.db.models import DO_NOTHING


class Team(models.Model):
    name = models.CharField(max_length=256, unique=True)
    details = models.TextField()

    # Display Team name instead of Object when calling a Team instance from database
    def __str__(self):
        return self.name


class Player(models.Model):
    name = models.CharField(max_length=256)
    number = models.IntegerField()
    age = models.IntegerField()
    position_in_field = models.CharField(max_length=256,
                                         choices=(('1', 'حارس'), ('2', 'مدافع'), ('3', 'وسط'), ('4', 'مهاجم')))
    is_captain = models.BooleanField(default=False)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)

    # Display playerName - clubName instead of Object
    # example: بنزيما - ريال مدريد
    def __str__(self):
        return '{} - {}'.format(self.name, self.team)


class GameScore(models.Model):
    first_team_relation = models.ForeignKey(Team, related_name='first_team', null=True, on_delete=DO_NOTHING)
    second_team_relation = models.ForeignKey(Team, related_name='second_team', null=True, on_delete=DO_NOTHING)
    first_team_score = models.IntegerField(default=0)
    second_team_score = models.IntegerField(default=0)
    game_date = models.DateTimeField(auto_now=True)

    # example: ليفربول 0 - 3 ريال مدريد
    def __str__(self):
        return '{} {} - {} {}'.format(self.first_team_relation.name, self.first_team_relation.name, self.second_team_score, self.second_team)

teams/forms.py
from django import forms
from django.forms import ModelForm
from crispy_forms import layout
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from teams.models import Team, GameScore, Player


class TeamForm(forms.Form):
    name = forms.CharField(label='اسم الفريق')
    details = forms.CharField(label='تفاصيل الفريق')


class PlayerForm(forms.Form):
    name = forms.CharField(label='اسم اللاعب')
    number = forms.IntegerField(label='رقم اللاعب')
    age = forms.IntegerField(label='عمر اللاعب')
    position_in_field = forms.CharField(label='الموقع في الملعب')
    is_captain = forms.BooleanField(label='هل هو قائد الفريق')
    team = forms.CharField(label='اسم الفريق')


class TeamModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TeamModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'اضافة'))

    class Meta:
        model = Team
        # fields = ['name', 'details']
        fields = '__all__'
        labels = {
            'name': 'اسم الفريق',
            'details': 'تفاصيل الفريق',
        }

        error_messages = {
            'name': {
                'unique': 'عذرا هذا الاسم مكرر, يرجى تغيير الاسم',
            }
        }


class PlayerModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PlayerModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'اضافة'))

    class Meta:
        model = Player

        fields = '__all__'
        labels = {
            'name': 'اسم اللاعب',
            'number': 'رقم اللاعب',
            'age': 'عمر اللاعب',
            'position_in_field': 'الموقع في الملعب',
            'is_captain': 'هل هو قائد الفريق',
            'team': 'فريق اللاعب',
        }

        error_messages = {
            'number': {
                'unique': 'عذرا هذا الرقم مأخود, يرجى اختيار رقم اخر',
            }
        }


class ScoreModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ScoreModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'اضافة'))

    class Meta:
        model = GameScore
        exclude = ['game_date']  # get all fields except game_date

        labels = {
            'first_team_relation': 'اسم الفريق الاول',
            'second_team_relation': 'اسم الفريق الثاني',
            'first_team_score': 'نتيجة الفريق الاول',
            'second_team_score': 'نتيجة الفريق الثاني',
        }

teams/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView

from teams.forms import TeamForm, TeamModelForm, ScoreModelForm, PlayerModelForm
from teams.models import Team, GameScore, Player


# Render teams using View class
class HomePageView(View):
    def get(self, request):
        # get all teams from database
        all_teams = Team.objects.all()

        # Send all teams to template as teams
        context = {
            "teams": all_teams
        }
        return render(request, 'home.html', context)


# Render teams using ListView class
class TeamsListView(ListView):
    model = Team
    template_name = 'teams_list.html'
    # Send all teams to template as teams
    context_object_name = 'teams'


class ScoresListView(ListView):
    model = GameScore
    template_name = 'scores_list.html'
    context_object_name = 'scores'

    def get_context_data(self, **kwargs):
        context = super(ScoresListView, self).get_context_data(**kwargs)
        context['form'] = ScoreModelForm()
        return context

    # Create a new game-score from form
    def post(self, request, *args, **kwargs):
        form = ScoreModelForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/scores/')


class TeamDetailsView(DetailView):
    model = Team
    template_name = 'team_details.html'
    context_object_name = 'team'
    slug_field = 'name'


class PlayerDetailsView(DetailView):
    model = Player
    template_name = 'player_details.html'
    context_object_name = 'player'
    slug_field = 'name'


class AddTeamView(View):

    def get(self, request):
        form = TeamModelForm()
        context = {'form': form}
        return render(request, 'add_team.html', context)

    def post(self, request):
        form = TeamModelForm(request.POST)
        # if form data are valid
        if form.is_valid():
            form.save()  # save data
            return redirect('/')  # redirect to home after saving
        # if form data are not valid
        else:
            context = {'form': form}
            return render(request, 'add_team.html', context)


class AddPlayerView(View):
    def get(self, request):
        form = PlayerModelForm()
        context = {'form': form}
        return render(request, 'add_player.html', context)

    def post(self, request):
        form = PlayerModelForm(request.POST)
        # if form data are valid
        if form.is_valid():
            form.save()  # save data
            return redirect('/')  # redirect to home after saving
        # if form data are not valid
        else:
            context = {'form': form}
            return render(request, 'add_player.html', context)

teams/templates/add_player.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} اضافة لاعب {% endblock %}

{% block content %}
    <form action="/add_player/" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="اضافة">
    </form>
{% endblock %}

teams/templates/add_score.html
{% load crispy_forms_tags %}

<form action="/scores/" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="اضافة">
</form>

teams/templates/add_team.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} اضافة فريق {% endblock %}

{% block content %}
    <form action="/add_team/" method="post">
        {% csrf_token %}
        {{ form|crispy }}
    </form>
{% endblock %}

teams/templates/home.html
{% extends 'base.html' %}
{% block title %} تسيير الفرق {% endblock %}

{% block content %}
    <section class="landing">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">نتائج المباريات</h2>
        </div>
        <div class="col-sm-12 col-md-6">
{#          <img src="./images/stats.svg" alt="">#}
        </div>
      </div>
    </section>

    <section class="about">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">اللاعبين</h2>
        </div>
        <div class="col-sm-12 col-md-6">
{#          <img src="./images/player.svg" alt="">#}
        </div>
      </div>
    </section>

    <section class="third">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">الفرق</h2>
        </div>
        <div class="col-sm-12 col-md-6">
{#          <img src="./images/team2.svg" alt="">#}
        </div>
      </div>
    </section>

    <section class="fourth">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">نتائج المباريات</h2>
        </div>
        <div class="col-sm-12 col-md-6">
{#          <img src="./images/score.svg" alt="">#}
        </div>
      </div>
    </section>

{% endblock %}

teams/templates/player_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <img class="icon-width" src="{% static 'images/ic_player.png' %}" alt="">

    {% if player.is_captain %}
        <h2> {{ player.name }} قائد {{ player.team }} </h2>
    {% else %}
        <h2> {{ player.name }} من {{ player.team }} </h2>
    {% endif %}

    <h3> رقم اللاعب {{ player.number }}  </h3>
    <h3> عمر اللاعب {{ player.age }} </h3>
    <h3> الموقع {{ player.get_position_in_field_display }} </h3>

{% endblock %}

teams/templates/scores_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} نتائج المباريات {% endblock %}

{% block content %}
    <div align="center">
        <img class="icon-width" src="{% static 'images/ic_game_score.png' %}" alt="">
    </div>
    <div align="center">
        {% include 'add_score.html' %}
    </div>
    {% for score in scores %}
        <div align="center">
            <!-- Didplay the date just once in the page -->
            {% ifchanged %}
                <h2> {{ score.game_date|date:'d-m-Y' }} </h2>
            {% endifchanged %}
            <h2> نتيجة مباراة {{ score.first_team_relation.name }} و {{ score.second_team_relation.name }} </h2>
            <h3> {{ score.first_team_score }} - {{ score.second_team_score }} </h3>
        </div>
    {% endfor %}

{% endblock %}

teams/templates/team_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <img class="icon-width" src="{% static 'images/ic_team.png' %}" alt="">

    <h2>{{ team.name }}</h2>
    <p>{{ team.details }}</p>

    {% for player in team.player_set.all %}
        <a href="/player/{{ player.name }}">
            <h3>{{ player.name }}</h3>
        </a>
    {% endfor %}

{% endblock %}

teams/templates/teams_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} قائمة الفرق {% endblock %}

{% block content %}

    <img class="icon-width" src="{% static 'images/ic_teams_list.png' %}" alt="">

    {% for team in teams %}
        <a href="/team/{{ team.name }}">
            <h2> {{ team.name }} </h2>
        </a>
        <p> {{ team.details }} </p>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title> {% block title %} نظام إدارة فرق كرة القدم {% endblock %} </title>

    <!-- Bootstrap  Latest compiled and minified CSS  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha256-L/W5Wfqfa0sdBNIKN9cG6QA5F2qx4qICmU2VgLruv9Y=" crossorigin="anonymous" />

    <!-- My Custom Css Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jomhuria&display=swap" rel="stylesheet">
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">نظام إدارة الفرق</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="/">الرئيسية<span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="/teams">قائمة الفرق</a>
          <a class="nav-item nav-link" href="/scores">نتائج المباريات</a>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        {% block content %}
        
        {% endblock %}
    </div>

</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">

  <head>
    <meta charset="utf-8">
    <title>Design</title>

    <!-- Bootstrap  Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" rel="stylesheet">
{#    <link href="https://fonts.googleapis.com/css2?family=Jomhuria&display=swap" rel="stylesheet">#}
  </head>
  <body>

    <section class="landing">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12">
          <h1 class="text-center">
              <a href="/">نظام إدارة فرق كرة القدم</a>
          </h1>
        </div>
        <div align="center" class="col-sm-12 banner">
            <img class="" src="{% static 'images/score.svg' %}" alt="banner image">
        </div>
      </div>
    </section>

    <section class="about">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">
              <a href="/add_player">اللاعبين</a>
          </h2>
        </div>
        <div class="col-sm-12 col-md-6">
            <img class="" src="{% static 'images/player.svg' %}" alt="player image">
        </div>
      </div>
    </section>

    <section class="third">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
            <img class="" src="{% static 'images/team2.svg' %}" alt="team image">
        </div>
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">
              <a href="/teams">الفرق</a>
          </h2>
        </div>
      </div>
    </section>

    <section class="fourth">
      <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-6">
          <h2 class="text-center">
              <a href="/scores">نتائج المباريات</a>
          </h2>
        </div>
        <div class="col-sm-12 col-md-6">
            <img class="" src="{% static 'images/stats.svg' %}" alt="score image">
        </div>
      </div>
    </section>

  </body>
</html>